# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
# yaml-language-server: ...
package: api
generate:
  std-http-server: true
  models: true
output: api.go
